"""add validator_application workflow

Revision ID: 2573138adad2
Revises: 29b40c848392
Create Date: 2025-08-31 14:34:12.733822
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2573138adad2'
down_revision: Union[str, None] = '29b40c848392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_definition',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_definition_key'), 'form_definition', ['key'], unique=True)
    op.create_index(op.f('ix_form_definition_role'), 'form_definition', ['role'], unique=False)
    op.create_table('verification_dimension',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_dimension_key'), 'verification_dimension', ['key'], unique=True)
    op.create_table('form_section',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_section_form_id'), 'form_section', ['form_id'], unique=False)
    op.create_table('questionnaire_import_batch',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['form_definition.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_catalog',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_dimension_id', sa.UUID(), nullable=True),
    sa.Column('applies_to_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('suggested_price_low_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggested_price_high_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_dimension_id'], ['verification_dimension.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_catalog_key'), 'service_catalog', ['key'], unique=True)
    op.create_table('validator_category',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_dimension_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_dimension_id'], ['verification_dimension.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_category_key'), 'validator_category', ['key'], unique=True)
    op.create_table('form_question',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('qtype', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_question_form_id'), 'form_question', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_question_key'), 'form_question', ['key'], unique=False)
    op.create_index(op.f('ix_form_question_section_id'), 'form_question', ['section_id'], unique=False)
    op.create_table('form_response',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('respondent_enterprise_id', sa.UUID(), nullable=True),
    sa.Column('respondent_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(respondent_enterprise_id IS NOT NULL) <> (respondent_user_id IS NOT NULL)', name='ck_form_resp_subject'),
    sa.ForeignKeyConstraint(['form_id'], ['form_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_response_form_id'), 'form_response', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_response_respondent_enterprise_id'), 'form_response', ['respondent_enterprise_id'], unique=False)
    op.create_index(op.f('ix_form_response_respondent_user_id'), 'form_response', ['respondent_user_id'], unique=False)
    op.create_index(op.f('ix_form_response_submitted_at'), 'form_response', ['submitted_at'], unique=False)
    op.create_table('questionnaire_import_error',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['questionnaire_import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_import_error_batch_id'), 'questionnaire_import_error', ['batch_id'], unique=False)
    op.create_table('service_recommendation',
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('service_key', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_key'], ['service_catalog.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'service_key', name='uq_service_reco_once')
    )
    op.create_index(op.f('ix_service_recommendation_enterprise_id'), 'service_recommendation', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_service_recommendation_service_key'), 'service_recommendation', ['service_key'], unique=False)
    op.create_table('term_sheet',
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.String(length=20), nullable=True),
    sa.Column('investment_amount_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valuation_cap_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_sheet_enterprise_id'), 'term_sheet', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_term_sheet_round_type'), 'term_sheet', ['round_type'], unique=False)
    op.create_index(op.f('ix_term_sheet_status'), 'term_sheet', ['status'], unique=False)
    op.create_table('validator_application',
    sa.Column('applicant_user_id', sa.UUID(), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'in_review', 'needs_more_info', 'approved', 'rejected', 'withdrawn', name='validator_application_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('application_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intelleges_questionnaire_id', sa.String(length=255), nullable=True),
    sa.Column('intelleges_status', sa.String(length=50), nullable=True),
    sa.Column('intelleges_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intelleges_response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_application_applicant_user_id'), 'validator_application', ['applicant_user_id'], unique=False)
    op.create_table('form_answer',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('value_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('value_currency_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['form_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_answer_once')
    )
    op.create_index(op.f('ix_form_answer_question_id'), 'form_answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_form_answer_response_id'), 'form_answer', ['response_id'], unique=False)
    op.create_table('form_option',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['form_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'value', name='uq_option_per_question')
    )
    op.create_index(op.f('ix_form_option_question_id'), 'form_option', ['question_id'], unique=False)
    op.create_table('safe_agreement',
    sa.Column('term_sheet_id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=True),
    sa.Column('post_money', sa.Boolean(), nullable=True),
    sa.Column('governing_law', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('esign_status', sa.String(length=20), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_sheet_id'], ['term_sheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safe_agreement_esign_status'), 'safe_agreement', ['esign_status'], unique=False)
    op.create_index(op.f('ix_safe_agreement_term_sheet_id'), 'safe_agreement', ['term_sheet_id'], unique=False)
    op.create_table('validator_profile',
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('response_sla_h', sa.Integer(), nullable=True),
    sa.Column('geographies', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['validator_application.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['validator_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_profile_category_id'), 'validator_profile', ['category_id'], unique=False)
    op.create_index(op.f('ix_validator_profile_enterprise_id'), 'validator_profile', ['enterprise_id'], unique=True)
    op.create_index(op.f('ix_validator_profile_is_public'), 'validator_profile', ['is_public'], unique=False)
    op.create_table('form_answer_option',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['form_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['form_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'option_id', name='uq_answer_option')
    )
    op.create_index(op.f('ix_form_answer_option_answer_id'), 'form_answer_option', ['answer_id'], unique=False)
    op.create_index(op.f('ix_form_answer_option_option_id'), 'form_answer_option', ['option_id'], unique=False)
    op.create_table('validator_industry',
    sa.Column('validator_profile_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_profile_id'], ['validator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validator_profile_id', 'industry_id', name='uq_validator_industry')
    )
    op.create_index(op.f('ix_validator_industry_industry_id'), 'validator_industry', ['industry_id'], unique=False)
    op.create_index(op.f('ix_validator_industry_validator_profile_id'), 'validator_industry', ['validator_profile_id'], unique=False)
    op.create_table('validator_service',
    sa.Column('validator_profile_id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('base_sla_h', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['verification_dimension.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validator_profile_id'], ['validator_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validator_profile_id', 'name', name='uq_validator_service_per_firm')
    )
    op.create_index(op.f('ix_validator_service_dimension_id'), 'validator_service', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_validator_service_is_active'), 'validator_service', ['is_active'], unique=False)
    op.create_index(op.f('ix_validator_service_validator_profile_id'), 'validator_service', ['validator_profile_id'], unique=False)
    op.create_table('validation_request',
    sa.Column('requester_enterprise_id', sa.UUID(), nullable=False),
    sa.Column('validator_enterprise_id', sa.UUID(), nullable=False),
    sa.Column('validator_service_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price_agreed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_split_validator_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payout_split_hric_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_transfer_group', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_enterprise_id'], ['enterprise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_service_id'], ['validator_service.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_request_requester_enterprise_id'), 'validation_request', ['requester_enterprise_id'], unique=False)
    op.create_index(op.f('ix_validation_request_status'), 'validation_request', ['status'], unique=False)
    op.create_index(op.f('ix_validation_request_stripe_payment_intent_id'), 'validation_request', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_validation_request_validator_enterprise_id'), 'validation_request', ['validator_enterprise_id'], unique=False)
    op.create_index(op.f('ix_validation_request_validator_service_id'), 'validation_request', ['validator_service_id'], unique=False)
    op.create_table('validation_deliverable',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['validation_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_deliverable_request_id'), 'validation_deliverable', ['request_id'], unique=False)
    op.create_table('validation_review',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['request_id'], ['validation_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_review_request_id'), 'validation_review', ['request_id'], unique=False)
    op.create_index(op.f('ix_validation_review_reviewer_id'), 'validation_review', ['reviewer_id'], unique=False)
    op.drop_index(op.f('idx_document_tags'), table_name='document', postgresql_using='gin')
    op.create_index('idx_doc_tags', 'document', ['tags'], unique=False, postgresql_using='gin')
    op.drop_column('document', 'download_count')
    op.drop_column('document', 'last_accessed_at')
    op.drop_column('document', 'expires_at')
    op.drop_column('document_types', 'validation_rules')
    op.drop_column('document_types', 'description')
    op.add_column('enterprise', sa.Column('industry_id', sa.UUID(), nullable=True))
    op.add_column('enterprise', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.add_column('enterprise', sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enterprise', sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_enterprise_industry_id'), 'enterprise', ['industry_id'], unique=False)
    op.create_index(op.f('ix_enterprise_stage_id'), 'enterprise', ['stage_id'], unique=False)
    op.create_foreign_key(None, 'enterprise', 'stage', ['stage_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'enterprise', 'industry', ['industry_id'], ['id'], ondelete='SET NULL')
    op.drop_column('enterprise', 'headquarters_address')
    op.add_column('enterprise_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enterprise_user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('unique_enterprise_user'), 'enterprise_user', type_='unique')
    op.drop_index(op.f('uq_enterprise_owner'), table_name='enterprise_user', postgresql_where="((role)::text = 'owner'::text)")
    op.create_index('uq_enterprise_one_owner', 'enterprise_user', ['enterprise_id'], unique=True, postgresql_where=sa.text("role='owner'"))
    op.create_unique_constraint('uq_enterprise_user', 'enterprise_user', ['enterprise_id', 'user_id'])
    op.drop_column('external_service_calls', 'error_message')
    op.drop_column('external_services', 'supported_document_types')
    op.drop_column('external_services', 'supported_countries')
    op.drop_column('external_services', 'average_response_time_seconds')
    op.drop_column('external_services', 'pricing_per_check')
    op.drop_column('external_services', 'success_rate')
    op.drop_column('funding_round', 'is_public')
    op.drop_column('funding_round', 'terms_summary')
    op.drop_column('funding_round', 'notes')
    op.drop_column('funding_round', 'use_of_funds')
    op.drop_constraint(op.f('uq_investor_geographic_focus'), 'investor_geographic_focus', type_='unique')
    op.create_unique_constraint('uq_investor_geo', 'investor_geographic_focus', ['investor_profile_id', 'geographic_area_id'])
    op.drop_index(op.f('idx_investor_profile_portfolio'), table_name='investor_profile', postgresql_using='gin')
    op.drop_column('investor_profile', 'investment_approach')
    op.drop_column('investor_profile', 'value_add_services')
    op.drop_column('investor_profile', 'portfolio_companies')
    op.add_column('messaging', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('messaging', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('messaging', 'replied_at')
    op.drop_column('messaging', 'is_deleted')
    op.drop_column('messaging', 'attachments')
    op.drop_column('messaging', 'read_at')
    op.add_column('secured_access', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('secured_access', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('unique_user_resource_access'), 'secured_access', type_='unique')
    op.create_unique_constraint('uq_user_resource', 'secured_access', ['user_id', 'resource_type', 'resource_id'])
    op.drop_column('secured_access', 'conditions')
    op.add_column('stage', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('stage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('startup_metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('startup_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_startup_metric_name'), table_name='startup_metrics')
    op.drop_index(op.f('ix_startup_metrics_metric_type'), table_name='startup_metrics')
    op.drop_constraint(op.f('uq_startup_metric_period'), 'startup_metrics', type_='unique')
    op.create_unique_constraint('uq_startup_metric_period', 'startup_metrics', ['startup_profile_id', 'metric_name', 'period_start', 'period_end'])
    op.create_index(op.f('ix_startup_metrics_metric_name'), 'startup_metrics', ['metric_name'], unique=False)
    op.drop_constraint(op.f('startup_metrics_created_by_fkey'), 'startup_metrics', type_='foreignkey')
    op.drop_column('startup_metrics', 'created_by')
    op.drop_column('startup_metrics', 'metric_type')
    op.drop_column('startup_metrics', 'notes')
    op.drop_column('startup_metrics', 'is_public')
    op.drop_index(op.f('idx_startup_metrics_traction'), table_name='startup_profile', postgresql_using='gin')
    op.drop_column('startup_profile', 'mrr_usd')
    op.drop_column('startup_profile', 'technical_founders_pct')
    op.drop_column('startup_profile', 'addressable_market')
    op.drop_column('startup_profile', 'market_size')
    op.drop_column('startup_profile', 'target_market')
    op.drop_column('startup_profile', 'previous_exits_pct')
    op.drop_column('startup_profile', 'monthly_growth_rate')
    op.drop_column('startup_profile', 'arr_usd')
    op.drop_column('startup_profile', 'value_proposition')
    op.drop_column('startup_profile', 'current_investors')
    op.drop_column('startup_profile', 'intellectual_property')
    op.drop_column('startup_profile', 'current_valuation_usd')
    op.drop_column('startup_profile', 'traction_metrics')
    op.drop_column('startup_profile', 'competitive_advantages')
    op.drop_column('startup_profile', 'regulatory_considerations')
    op.drop_column('startup_profile', 'business_model')
    op.drop_column('startup_profile', 'customer_count')
    op.drop_column('startup_profile', 'revenue_model')
    op.drop_index(op.f('ix_subscription_stripe_status_raw'), table_name='subscription')
    op.drop_column('subscription', 'stripe_product_id')
    op.drop_column('subscription', 'collection_method')
    op.drop_column('subscription', 'cancellation_reason')
    op.drop_column('subscription', 'stripe_price_id')
    op.drop_column('subscription', 'auto_renew')
    op.drop_column('subscription', 'payment_frequency')
    op.drop_column('subscription', 'end_date')
    op.drop_column('subscription', 'trial_end_date')
    op.drop_column('subscription', 'cancel_at_period_end')
    op.drop_column('subscription', 'billing_cycle_anchor')
    op.drop_column('subscription', 'current_period_start')
    op.drop_column('subscription', 'cancelled_at')
    op.drop_column('subscription', 'default_payment_method_id')
    op.drop_column('subscription', 'stripe_status_raw')
    op.drop_column('subscription', 'next_billing_date')
    op.drop_column('user_plan', 'stripe_product_id')
    op.drop_column('user_plan', 'max_connections')
    op.drop_column('user_plan', 'stripe_price_id_monthly')
    op.drop_column('user_plan', 'stripe_price_id_annual')
    op.drop_column('user_plan', 'max_storage_gb')
    op.drop_column('verification_documents', 'validation_results')
    op.drop_column('verification_documents', 'rejection_reason')
    op.drop_column('verification_documents', 'ocr_text')
    op.drop_column('verification_documents', 'extracted_data')
    op.alter_column('verification_levels', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('verification_levels', 'processing_time_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('verification_levels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_verifications_user_level'), table_name='verifications')
    op.drop_column('verifications', 'expires_at')
    op.drop_column('verifications', 'rejection_reason')
    op.drop_column('verifications', 'risk_factors')
    op.drop_column('verifications', 'third_party_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('third_party_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('verifications', sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('verifications', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_verifications_user_level'), 'verifications', ['user_id', 'verification_level_id'], unique=False)
    op.alter_column('verification_levels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('verification_levels', 'processing_time_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('verification_levels', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('verification_documents', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('verification_documents', sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verification_documents', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verification_documents', sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_plan', sa.Column('max_storage_gb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_plan', sa.Column('stripe_price_id_annual', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_plan', sa.Column('stripe_price_id_monthly', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_plan', sa.Column('max_connections', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_plan', sa.Column('stripe_product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('next_billing_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('stripe_status_raw', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('default_payment_method_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('billing_cycle_anchor', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('trial_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('payment_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('stripe_price_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('collection_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('stripe_product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_subscription_stripe_status_raw'), 'subscription', ['stripe_status_raw'], unique=False)
    op.add_column('startup_profile', sa.Column('revenue_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('customer_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('business_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('regulatory_considerations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('competitive_advantages', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('traction_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('current_valuation_usd', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('intellectual_property', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('current_investors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('value_proposition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('arr_usd', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('monthly_growth_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('previous_exits_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('target_market', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('market_size', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('addressable_market', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('technical_founders_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('startup_profile', sa.Column('mrr_usd', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_startup_metrics_traction'), 'startup_profile', ['traction_metrics'], unique=False, postgresql_using='gin')
    op.add_column('startup_metrics', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('startup_metrics', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('startup_metrics', sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('startup_metrics', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('startup_metrics_created_by_fkey'), 'startup_metrics', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_startup_metrics_metric_name'), table_name='startup_metrics')
    op.drop_constraint('uq_startup_metric_period', 'startup_metrics', type_='unique')
    op.create_unique_constraint(op.f('uq_startup_metric_period'), 'startup_metrics', ['startup_profile_id', 'metric_type', 'metric_name', 'period_start', 'period_end'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_startup_metrics_metric_type'), 'startup_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('idx_startup_metric_name'), 'startup_metrics', ['metric_name'], unique=False)
    op.drop_column('startup_metrics', 'updated_at')
    op.drop_column('startup_metrics', 'created_at')
    op.alter_column('stage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('stage', 'updated_at')
    op.add_column('secured_access', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_resource', 'secured_access', type_='unique')
    op.create_unique_constraint(op.f('unique_user_resource_access'), 'secured_access', ['user_id', 'resource_type', 'resource_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('secured_access', 'updated_at')
    op.drop_column('secured_access', 'created_at')
    op.add_column('messaging', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messaging', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messaging', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messaging', sa.Column('replied_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('messaging', 'updated_at')
    op.drop_column('messaging', 'created_at')
    op.add_column('investor_profile', sa.Column('portfolio_companies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('value_add_services', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('investment_approach', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_investor_profile_portfolio'), 'investor_profile', ['portfolio_companies'], unique=False, postgresql_using='gin')
    op.drop_constraint('uq_investor_geo', 'investor_geographic_focus', type_='unique')
    op.create_unique_constraint(op.f('uq_investor_geographic_focus'), 'investor_geographic_focus', ['investor_profile_id', 'geographic_area_id'], postgresql_nulls_not_distinct=False)
    op.add_column('funding_round', sa.Column('use_of_funds', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('funding_round', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('funding_round', sa.Column('terms_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('funding_round', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('external_services', sa.Column('success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('external_services', sa.Column('pricing_per_check', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('external_services', sa.Column('average_response_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('external_services', sa.Column('supported_countries', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('external_services', sa.Column('supported_document_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('external_service_calls', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_enterprise_user', 'enterprise_user', type_='unique')
    op.drop_index('uq_enterprise_one_owner', table_name='enterprise_user', postgresql_where=sa.text("role='owner'"))
    op.create_index(op.f('uq_enterprise_owner'), 'enterprise_user', ['enterprise_id'], unique=True, postgresql_where="((role)::text = 'owner'::text)")
    op.create_unique_constraint(op.f('unique_enterprise_user'), 'enterprise_user', ['enterprise_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('enterprise_user', 'updated_at')
    op.drop_column('enterprise_user', 'created_at')
    op.add_column('enterprise', sa.Column('headquarters_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enterprise', type_='foreignkey')
    op.drop_constraint(None, 'enterprise', type_='foreignkey')
    op.drop_index(op.f('ix_enterprise_stage_id'), table_name='enterprise')
    op.drop_index(op.f('ix_enterprise_industry_id'), table_name='enterprise')
    op.drop_column('enterprise', 'social_media')
    op.drop_column('enterprise', 'contact_info')
    op.drop_column('enterprise', 'stage_id')
    op.drop_column('enterprise', 'industry_id')
    op.add_column('document_types', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_types', sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('idx_doc_tags', table_name='document', postgresql_using='gin')
    op.create_index(op.f('idx_document_tags'), 'document', ['tags'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_validation_review_reviewer_id'), table_name='validation_review')
    op.drop_index(op.f('ix_validation_review_request_id'), table_name='validation_review')
    op.drop_table('validation_review')
    op.drop_index(op.f('ix_validation_deliverable_request_id'), table_name='validation_deliverable')
    op.drop_table('validation_deliverable')
    op.drop_index(op.f('ix_validation_request_validator_service_id'), table_name='validation_request')
    op.drop_index(op.f('ix_validation_request_validator_enterprise_id'), table_name='validation_request')
    op.drop_index(op.f('ix_validation_request_stripe_payment_intent_id'), table_name='validation_request')
    op.drop_index(op.f('ix_validation_request_status'), table_name='validation_request')
    op.drop_index(op.f('ix_validation_request_requester_enterprise_id'), table_name='validation_request')
    op.drop_table('validation_request')
    op.drop_index(op.f('ix_validator_service_validator_profile_id'), table_name='validator_service')
    op.drop_index(op.f('ix_validator_service_is_active'), table_name='validator_service')
    op.drop_index(op.f('ix_validator_service_dimension_id'), table_name='validator_service')
    op.drop_table('validator_service')
    op.drop_index(op.f('ix_validator_industry_validator_profile_id'), table_name='validator_industry')
    op.drop_index(op.f('ix_validator_industry_industry_id'), table_name='validator_industry')
    op.drop_table('validator_industry')
    op.drop_index(op.f('ix_form_answer_option_option_id'), table_name='form_answer_option')
    op.drop_index(op.f('ix_form_answer_option_answer_id'), table_name='form_answer_option')
    op.drop_table('form_answer_option')
    op.drop_index(op.f('ix_validator_profile_is_public'), table_name='validator_profile')
    op.drop_index(op.f('ix_validator_profile_enterprise_id'), table_name='validator_profile')
    op.drop_index(op.f('ix_validator_profile_category_id'), table_name='validator_profile')
    op.drop_table('validator_profile')
    op.drop_index(op.f('ix_safe_agreement_term_sheet_id'), table_name='safe_agreement')
    op.drop_index(op.f('ix_safe_agreement_esign_status'), table_name='safe_agreement')
    op.drop_table('safe_agreement')
    op.drop_index(op.f('ix_form_option_question_id'), table_name='form_option')
    op.drop_table('form_option')
    op.drop_index(op.f('ix_form_answer_response_id'), table_name='form_answer')
    op.drop_index(op.f('ix_form_answer_question_id'), table_name='form_answer')
    op.drop_table('form_answer')
    op.drop_index(op.f('ix_validator_application_applicant_user_id'), table_name='validator_application')
    op.drop_table('validator_application')
    op.drop_index(op.f('ix_term_sheet_status'), table_name='term_sheet')
    op.drop_index(op.f('ix_term_sheet_round_type'), table_name='term_sheet')
    op.drop_index(op.f('ix_term_sheet_enterprise_id'), table_name='term_sheet')
    op.drop_table('term_sheet')
    op.drop_index(op.f('ix_service_recommendation_service_key'), table_name='service_recommendation')
    op.drop_index(op.f('ix_service_recommendation_enterprise_id'), table_name='service_recommendation')
    op.drop_table('service_recommendation')
    op.drop_index(op.f('ix_questionnaire_import_error_batch_id'), table_name='questionnaire_import_error')
    op.drop_table('questionnaire_import_error')
    op.drop_index(op.f('ix_form_response_submitted_at'), table_name='form_response')
    op.drop_index(op.f('ix_form_response_respondent_user_id'), table_name='form_response')
    op.drop_index(op.f('ix_form_response_respondent_enterprise_id'), table_name='form_response')
    op.drop_index(op.f('ix_form_response_form_id'), table_name='form_response')
    op.drop_table('form_response')
    op.drop_index(op.f('ix_form_question_section_id'), table_name='form_question')
    op.drop_index(op.f('ix_form_question_key'), table_name='form_question')
    op.drop_index(op.f('ix_form_question_form_id'), table_name='form_question')
    op.drop_table('form_question')
    op.drop_index(op.f('ix_validator_category_key'), table_name='validator_category')
    op.drop_table('validator_category')
    op.drop_index(op.f('ix_service_catalog_key'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_table('questionnaire_import_batch')
    op.drop_index(op.f('ix_form_section_form_id'), table_name='form_section')
    op.drop_table('form_section')
    op.drop_index(op.f('ix_verification_dimension_key'), table_name='verification_dimension')
    op.drop_table('verification_dimension')
    op.drop_index(op.f('ix_form_definition_role'), table_name='form_definition')
    op.drop_index(op.f('ix_form_definition_key'), table_name='form_definition')
    op.drop_table('form_definition')
    # ### end Alembic commands ###