"""initial schema

Revision ID: 314b2edbf95c
Revises: 
Create Date: 2025-07-25 11:00:45.367813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '314b2edbf95c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    op.alter_column('document', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('document', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('document', 'tags',
        existing_type=sa.Text(),  # or whatever it was
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
        postgresql_using="tags::VARCHAR[]")
    op.drop_column('document', 'original_filename')
    op.drop_column('document', 'document_type')
    op.drop_column('document', 'file_type')
    op.drop_column('document', 'updated_at')
    op.drop_column('document', 'mime_type')
    op.drop_column('document', 'is_public')
    op.drop_column('document', 'file_size')
    op.drop_column('document', 'description')
    op.drop_column('document', 'download_count')
    op.drop_column('document', 'is_deleted')
    op.alter_column('document_access', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_access', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('document_access_granted_by_fkey'), 'document_access', type_='foreignkey')
    op.drop_column('document_access', 'notes')
    op.drop_column('document_access', 'granted_by')
    op.drop_column('document_access', 'expires_at')
    op.drop_column('document_access', 'revoked_at')
    op.drop_column('document_access', 'is_active')
    op.add_column('enterprise', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('enterprise', sa.Column('financials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('enterprise', 'founded_date')
    op.drop_column('enterprise', 'competitors')
    op.drop_column('enterprise', 'market_size')
    op.drop_column('enterprise', 'company_name')
    op.drop_column('enterprise', 'funding_stage')
    op.drop_column('enterprise', 'looking_for_strategic_value')
    op.drop_column('enterprise', 'company_description')
    op.drop_column('enterprise', 'monthly_revenue')
    op.drop_column('enterprise', 'updated_at')
    op.drop_column('enterprise', 'competitive_advantage')
    op.drop_column('enterprise', 'runway_months')
    op.drop_column('enterprise', 'use_of_funds')
    op.drop_column('enterprise', 'burn_rate')
    op.drop_column('enterprise', 'subscription_tier')
    op.drop_column('enterprise', 'advisors')
    op.drop_column('enterprise', 'gross_margin')
    op.drop_column('enterprise', 'funding_amount_seeking')
    op.drop_column('enterprise', 'geographic_investor_preference')
    op.drop_column('enterprise', 'monthly_growth_rate')
    op.drop_column('enterprise', 'previous_funding_rounds')
    op.drop_column('enterprise', 'funding_amount_raised')
    op.drop_column('enterprise', 'headline')
    op.drop_column('enterprise', 'location')
    op.drop_column('enterprise', 'employee_count')
    op.drop_column('enterprise', 'key_team_members')
    op.drop_column('enterprise', 'preferred_investor_types')
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('event', 'agenda',
            existing_type=sa.TEXT(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using="agenda::jsonb")
    op.alter_column('event', 'presenters',
            existing_type=sa.TEXT(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using="presenters::jsonb")
    op.drop_column('event', 'capacity')
    op.drop_column('event', 'price')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'summary')
    op.drop_column('event', 'is_members_only')
    op.drop_column('event', 'location')
    op.drop_column('event', 'event_type')
    op.drop_column('event', 'status')
    op.alter_column('event_registration', 'answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('event_registration', 'reviewer_email')
    op.drop_column('event_registration', 'reviewed_at')
    op.drop_column('event_registration', 'updated_at')
    op.drop_column('event_registration', 'meeting_preference')
    op.drop_column('event_registration', 'role')
    op.alter_column('investor_profile', 'industries',
                existing_type=sa.TEXT(),
                type_=postgresql.ARRAY(sa.String()),
                existing_nullable=True,
                postgresql_using="industries::VARCHAR[]")
    op.alter_column('investor_profile', 'investment_stages',
            existing_type=sa.TEXT(),
            type_=postgresql.ARRAY(sa.String()),
            existing_nullable=True,
            postgresql_using="investment_stages::VARCHAR[]")
    op.alter_column('investor_profile', 'geographic_focus',
            existing_type=sa.TEXT(),
            type_=postgresql.ARRAY(sa.String()),
            existing_nullable=True,
            postgresql_using="geographic_focus::VARCHAR[]")
    op.create_unique_constraint(None, 'investor_profile', ['user_id'])
    op.drop_column('investor_profile', 'board_experience')
    op.drop_column('investor_profile', 'updated_at')
    op.drop_column('investor_profile', 'headline')
    op.drop_column('investor_profile', 'investment_experience')
    op.drop_column('investor_profile', 'net_worth')
    op.drop_column('investor_profile', 'annual_income')
    op.drop_column('investor_profile', 'expertise_areas')
    op.drop_column('investor_profile', 'subscription_tier')
    op.add_column('like', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('unique_like', 'like', ['user_id', 'enterprise_id'])
    op.drop_constraint(op.f('like_investor_id_fkey'), 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'])
    op.drop_column('like', 'investor_id')
    op.alter_column('message', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('message', 'recipient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('message', 'attachments',
            existing_type=sa.TEXT(),
            type_=postgresql.ARRAY(sa.String()),
            existing_nullable=True,
            postgresql_using="attachments::VARCHAR[]")
    op.drop_column('message', 'subject')
    # Step 1: Add nullable column first
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))

    # Step 2: Fill existing rows with a default (e.g., 'investor')
    op.execute("UPDATE \"user\" SET role = 'investor' WHERE role IS NULL")

    # Step 3: Alter column to be non-nullable
    op.alter_column('user', 'role', nullable=False)

    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'subscription_tier')
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('subscription_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'role')
    op.add_column('message', sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('message', 'attachments',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('message', 'recipient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('message', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('like', sa.Column('investor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key(op.f('like_investor_id_fkey'), 'like', 'user', ['investor_id'], ['id'])
    op.drop_constraint('unique_like', 'like', type_='unique')
    op.drop_column('like', 'user_id')
    op.add_column('investor_profile', sa.Column('subscription_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('expertise_areas', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('annual_income', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('net_worth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('investment_experience', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('headline', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('investor_profile', sa.Column('board_experience', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'investor_profile', type_='unique')
    op.alter_column('investor_profile', 'geographic_focus',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investor_profile', 'investment_stages',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investor_profile', 'industries',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('event_registration', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('event_registration', sa.Column('meeting_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('event_registration', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('event_registration', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_registration', sa.Column('reviewer_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('event_registration', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('event', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('is_members_only', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('summary', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('event', 'presenters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event', 'agenda',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('enterprise', sa.Column('preferred_investor_types', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('key_team_members', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('headline', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('funding_amount_raised', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('previous_funding_rounds', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('monthly_growth_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('geographic_investor_preference', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('funding_amount_seeking', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('gross_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('advisors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('subscription_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('burn_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('use_of_funds', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('runway_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('competitive_advantage', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('monthly_revenue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('company_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('looking_for_strategic_value', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('funding_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('company_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('enterprise', sa.Column('market_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('competitors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enterprise', sa.Column('founded_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('enterprise', 'financials')
    op.drop_column('enterprise', 'name')
    op.add_column('document_access', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('document_access', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('document_access', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('document_access', sa.Column('granted_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('document_access', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_access_granted_by_fkey'), 'document_access', 'user', ['granted_by'], ['id'])
    op.alter_column('document_access', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_access', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('document', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('document', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('document', 'file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('document', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enterprise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('compatibility_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('match_reasons', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('match_algorithm_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('match_score_breakdown', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('investor_interest', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('enterprise_interest', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['user.id'], name=op.f('match_enterprise_id_fkey')),
    sa.ForeignKeyConstraint(['investor_id'], ['user.id'], name=op.f('match_investor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('match_pkey'))
    )
    op.drop_table('subscription')
    # ### end Alembic commands ###
