"""fix validation deliverable fk ambiguity

Revision ID: 43d559965c80
Revises: 2573138adad2
Create Date: 2025-08-31 15:51:42.091364
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d559965c80'
down_revision: Union[str, None] = '2573138adad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_deliverable', sa.Column('validation_request_id', sa.UUID(), nullable=False))
    op.alter_column('validation_deliverable', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_validation_deliverable_request_id'), table_name='validation_deliverable')
    op.create_index(op.f('ix_validation_deliverable_validation_request_id'), 'validation_deliverable', ['validation_request_id'], unique=False)
    op.drop_constraint(op.f('validation_deliverable_request_id_fkey'), 'validation_deliverable', type_='foreignkey')
    op.create_foreign_key(None, 'validation_deliverable', 'validation_request', ['validation_request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('validation_deliverable', 'request_id')
    op.alter_column('validation_request', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_request', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.add_column('validation_deliverable', sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'validation_deliverable', type_='foreignkey')
    op.create_foreign_key(op.f('validation_deliverable_request_id_fkey'), 'validation_deliverable', 'validation_request', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_validation_deliverable_validation_request_id'), table_name='validation_deliverable')
    op.create_index(op.f('ix_validation_deliverable_request_id'), 'validation_deliverable', ['request_id'], unique=False)
    op.alter_column('validation_deliverable', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('validation_deliverable', 'validation_request_id')
    # ### end Alembic commands ###