"""verified_status

Revision ID: 4a3d691c5c5b
Revises: 23a81af5f8e9
Create Date: 2025-08-31 16:40:51.750280
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3d691c5c5b'
down_revision: Union[str, None] = '23a81af5f8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startup_profile', sa.Column('verified_status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_startup_profile_verified_status'), 'startup_profile', ['verified_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_profile_verified_status'), table_name='startup_profile')
    op.drop_column('startup_profile', 'verified_status')
    # ### end Alembic commands ###