"""Add location and funding_needed

Revision ID: 658ff1d91439
Revises: 9d4e760eab2d
Create Date: 2025-07-29 14:29:08.616527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658ff1d91439'
down_revision = '9d4e760eab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('funding_needed', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.drop_column('funding_needed')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
