"""add verification models inline

Revision ID: 78aa9cbb343c
Revises: 90edb13c35f3
Create Date: 2025-08-10 08:42:47.730865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78aa9cbb343c'
down_revision = '90edb13c35f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('accepted_formats', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("user_type IN ('investor','startup')", name='check_doc_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_services',
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=False),
    sa.Column('api_version', sa.String(length=20), nullable=True),
    sa.Column('supported_countries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supported_document_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pricing_per_check', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('provider_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verification_levels',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("user_type IN ('investor','startup')", name='check_vlevel_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_rules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("user_type IN ('investor','startup')", name='check_rule_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_providers',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geographic_coverage', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('languages_supported', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('base_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=True),
    sa.Column('average_turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name='check_provider_rating'),
    sa.ForeignKeyConstraint(['category_id'], ['provider_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_providers_category_id'), 'service_providers', ['category_id'], unique=False)
    op.create_table('verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verification_level_id', sa.UUID(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('third_party_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_progress','under_review','approved','rejected','expired')", name='check_ver_status'),
    sa.CheckConstraint("user_type IN ('investor','startup')", name='check_ver_user_type'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='check_ver_risk_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_level_id'], ['verification_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verifications_user_level', 'verifications', ['user_id', 'verification_level_id'], unique=False)
    op.create_index(op.f('ix_verifications_initiated_at'), 'verifications', ['initiated_at'], unique=False)
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_verifications_verification_level_id'), 'verifications', ['verification_level_id'], unique=False)
    op.create_table('external_service_calls',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('call_type', sa.String(length=100), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','success','failed','timeout')", name='check_call_status'),
    sa.ForeignKeyConstraint(['service_id'], ['external_services.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_service_calls_service_id'), 'external_service_calls', ['service_id'], unique=False)
    op.create_index(op.f('ix_external_service_calls_verification_id'), 'external_service_calls', ['verification_id'], unique=False)
    op.create_table('provider_reviews',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('response_time_rating', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('is_verified_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('communication_rating IS NULL OR (communication_rating >= 1 AND communication_rating <= 5)', name='check_comm_rating'),
    sa.CheckConstraint('quality_rating IS NULL OR (quality_rating >= 1 AND quality_rating <= 5)', name='check_quality_rating'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_review_rating'),
    sa.CheckConstraint('response_time_rating IS NULL OR (response_time_rating >= 1 AND response_time_rating <= 5)', name='check_resp_time_rating'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_reviews_provider_id'), 'provider_reviews', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_reviews_user_id'), 'provider_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_provider_reviews_verification_id'), 'provider_reviews', ['verification_id'], unique=False)
    op.create_table('provider_services',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_services_provider_id'), 'provider_services', ['provider_id'], unique=False)
    op.create_table('verification_audit_log',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_audit_log_created_at'), 'verification_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_audit_log_verification_id'), 'verification_audit_log', ['verification_id'], unique=False)
    op.create_table('verification_documents',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','processing','approved','rejected')", name='check_document_status'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_documents_document_type_id'), 'verification_documents', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_verification_documents_status'), 'verification_documents', ['status'], unique=False)
    op.create_index(op.f('ix_verification_documents_uploaded_at'), 'verification_documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_verification_documents_verification_id'), 'verification_documents', ['verification_id'], unique=False)
    op.create_table('verification_notifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_notifications_recipient_id'), 'verification_notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_verification_notifications_verification_id'), 'verification_notifications', ['verification_id'], unique=False)
    op.create_table('verification_steps',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_progress','completed','failed','skipped')", name='check_step_status'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_steps_verification_id'), 'verification_steps', ['verification_id'], unique=False)
    op.create_table('verification_assignments',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('assigned','in_progress','completed','failed','cancelled')", name='check_assignment_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['provider_services.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_assignments_provider_id'), 'verification_assignments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_verification_assignments_service_id'), 'verification_assignments', ['service_id'], unique=False)
    op.create_index(op.f('ix_verification_assignments_status'), 'verification_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_verification_assignments_verification_id'), 'verification_assignments', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_assignments_verification_id'), table_name='verification_assignments')
    op.drop_index(op.f('ix_verification_assignments_status'), table_name='verification_assignments')
    op.drop_index(op.f('ix_verification_assignments_service_id'), table_name='verification_assignments')
    op.drop_index(op.f('ix_verification_assignments_provider_id'), table_name='verification_assignments')
    op.drop_table('verification_assignments')
    op.drop_index(op.f('ix_verification_steps_verification_id'), table_name='verification_steps')
    op.drop_table('verification_steps')
    op.drop_index(op.f('ix_verification_notifications_verification_id'), table_name='verification_notifications')
    op.drop_index(op.f('ix_verification_notifications_recipient_id'), table_name='verification_notifications')
    op.drop_table('verification_notifications')
    op.drop_index(op.f('ix_verification_documents_verification_id'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_uploaded_at'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_status'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_document_type_id'), table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index(op.f('ix_verification_audit_log_verification_id'), table_name='verification_audit_log')
    op.drop_index(op.f('ix_verification_audit_log_created_at'), table_name='verification_audit_log')
    op.drop_table('verification_audit_log')
    op.drop_index(op.f('ix_provider_services_provider_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_index(op.f('ix_provider_reviews_verification_id'), table_name='provider_reviews')
    op.drop_index(op.f('ix_provider_reviews_user_id'), table_name='provider_reviews')
    op.drop_index(op.f('ix_provider_reviews_provider_id'), table_name='provider_reviews')
    op.drop_table('provider_reviews')
    op.drop_index(op.f('ix_external_service_calls_verification_id'), table_name='external_service_calls')
    op.drop_index(op.f('ix_external_service_calls_service_id'), table_name='external_service_calls')
    op.drop_table('external_service_calls')
    op.drop_index(op.f('ix_verifications_verification_level_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_initiated_at'), table_name='verifications')
    op.drop_index('idx_verifications_user_level', table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_service_providers_category_id'), table_name='service_providers')
    op.drop_table('service_providers')
    op.drop_table('verification_rules')
    op.drop_table('verification_levels')
    op.drop_table('provider_categories')
    op.drop_table('external_services')
    op.drop_table('document_types')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
