"""new matches

Revision ID: 797b1ea0cc55
Revises: 78aa9cbb343c
Create Date: 2025-08-10 16:18:20.250924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797b1ea0cc55'
down_revision = '78aa9cbb343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_profile', sa.Column('headline_tags', sa.ARRAY(sa.String()), nullable=True))
    op.create_index('idx_enterprise_profile_headline_tags', 'enterprise_profile', ['headline_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_startup_metric_name', 'startup_metrics', ['metric_name'], unique=False)
    op.add_column('startup_profile', sa.Column('mrr_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('startup_profile', sa.Column('arr_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('startup_profile', sa.Column('current_valuation_usd', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('startup_profile', sa.Column('current_investors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('startup_profile', sa.Column('technical_founders_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('startup_profile', sa.Column('previous_exits_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startup_profile', 'previous_exits_pct')
    op.drop_column('startup_profile', 'technical_founders_pct')
    op.drop_column('startup_profile', 'current_investors')
    op.drop_column('startup_profile', 'current_valuation_usd')
    op.drop_column('startup_profile', 'arr_usd')
    op.drop_column('startup_profile', 'mrr_usd')
    op.drop_index('idx_startup_metric_name', table_name='startup_metrics')
    op.drop_index('idx_enterprise_profile_headline_tags', table_name='enterprise_profile', postgresql_using='gin')
    op.drop_column('enterprise_profile', 'headline_tags')
    # ### end Alembic commands ###
