"""Make enterprise fields nullable for progressive profile completion

Revision ID: 8407b1f71cff
Revises: d7cbb1deb160
Create Date: 2025-08-03 07:39:50.772107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8407b1f71cff'
down_revision = 'd7cbb1deb160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('is_actively_fundraising',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_actively_fundraising',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
