"""post-baseline changes (final)

Revision ID: 90edb13c35f3
Revises: eaf864580b38
Create Date: 2025-08-09 21:37:26.441921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90edb13c35f3'
down_revision = 'eaf864580b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geographic_area',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_area_name'), 'geographic_area', ['name'], unique=True)
    op.create_table('investor_geographic_focus',
    sa.Column('investor_profile_id', sa.UUID(), nullable=False),
    sa.Column('geographic_area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geographic_area_id'], ['geographic_area.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor_profile_id', 'geographic_area_id', name='uq_investor_geographic_focus')
    )
    op.create_index(op.f('ix_investor_geographic_focus_geographic_area_id'), 'investor_geographic_focus', ['geographic_area_id'], unique=False)
    op.create_index(op.f('ix_investor_geographic_focus_investor_profile_id'), 'investor_geographic_focus', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_enterprise_user_invited_by'), 'enterprise_user', ['invited_by'], unique=False)
    op.drop_index(op.f('idx_investment_preferences_industries'), table_name='investment_preferences', postgresql_using='gin')
    op.drop_index(op.f('idx_investment_preferences_stages'), table_name='investment_preferences', postgresql_using='gin')
    op.drop_column('investment_preferences', 'geographic_preferences')
    op.drop_column('investment_preferences', 'preferred_stages')
    op.drop_column('investment_preferences', 'preferred_industries')
    op.drop_index(op.f('idx_investor_profile_geo'), table_name='investor_profile', postgresql_using='gin')
    op.drop_column('investor_profile', 'geographic_focus')
    op.add_column('users', sa.Column('location', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_location'), table_name='users')
    op.drop_column('users', 'location')
    op.add_column('investor_profile', sa.Column('geographic_focus', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_investor_profile_geo'), 'investor_profile', ['geographic_focus'], unique=False, postgresql_using='gin')
    op.add_column('investment_preferences', sa.Column('preferred_industries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('investment_preferences', sa.Column('preferred_stages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('investment_preferences', sa.Column('geographic_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_investment_preferences_stages'), 'investment_preferences', ['preferred_stages'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_investment_preferences_industries'), 'investment_preferences', ['preferred_industries'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_enterprise_user_invited_by'), table_name='enterprise_user')
    op.drop_index(op.f('ix_investor_geographic_focus_investor_profile_id'), table_name='investor_geographic_focus')
    op.drop_index(op.f('ix_investor_geographic_focus_geographic_area_id'), table_name='investor_geographic_focus')
    op.drop_table('investor_geographic_focus')
    op.drop_index(op.f('ix_geographic_area_name'), table_name='geographic_area')
    op.drop_table('geographic_area')
    # ### end Alembic commands ###
