"""intelleges API I

Revision ID: 96a876a53d02
Revises: 205005e8a20f
Create Date: 2025-09-01 10:02:20.533965
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a876a53d02'
down_revision: Union[str, None] = '205005e8a20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelleges_registration',
    sa.Column('registration_id', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country_of_origin', sa.String(length=3), nullable=True),
    sa.Column('product_tier', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('questionnaire_link', sa.Text(), nullable=True),
    sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('answers_csv_path', sa.String(length=1000), nullable=True),
    sa.Column('answers_csv_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED','EMAIL_SUBMITTED','EMAIL_VERIFIED','QUESTIONNAIRE_LINK_ISSUED','IN_PROGRESS','COMPLETED')", name='ck_intelleges_status_values'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelleges_registration_email'), 'intelleges_registration', ['email'], unique=False)
    op.create_index(op.f('ix_intelleges_registration_idempotency_key'), 'intelleges_registration', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_intelleges_registration_registration_id'), 'intelleges_registration', ['registration_id'], unique=True)
    op.create_index(op.f('ix_intelleges_registration_status'), 'intelleges_registration', ['status'], unique=False)
    op.create_index(op.f('ix_intelleges_registration_user_id'), 'intelleges_registration', ['user_id'], unique=False)
    op.create_index('uq_intelleges_active_per_email_tier', 'intelleges_registration', [sa.literal_column('lower(email)'), 'product_tier'], unique=True, postgresql_where=sa.text("status <> 'COMPLETED'"))
    op.create_table('intelleges_event',
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('registration_id', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_db_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_db_id'], ['intelleges_registration.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelleges_event_event_id'), 'intelleges_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_intelleges_event_occurred_at_utc'), 'intelleges_event', ['occurred_at_utc'], unique=False)
    op.create_index(op.f('ix_intelleges_event_registration_id'), 'intelleges_event', ['registration_id'], unique=False)
    op.create_index(op.f('ix_intelleges_event_type'), 'intelleges_event', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelleges_event_type'), table_name='intelleges_event')
    op.drop_index(op.f('ix_intelleges_event_registration_id'), table_name='intelleges_event')
    op.drop_index(op.f('ix_intelleges_event_occurred_at_utc'), table_name='intelleges_event')
    op.drop_index(op.f('ix_intelleges_event_event_id'), table_name='intelleges_event')
    op.drop_table('intelleges_event')
    op.drop_index('uq_intelleges_active_per_email_tier', table_name='intelleges_registration', postgresql_where=sa.text("status <> 'COMPLETED'"))
    op.drop_index(op.f('ix_intelleges_registration_user_id'), table_name='intelleges_registration')
    op.drop_index(op.f('ix_intelleges_registration_status'), table_name='intelleges_registration')
    op.drop_index(op.f('ix_intelleges_registration_registration_id'), table_name='intelleges_registration')
    op.drop_index(op.f('ix_intelleges_registration_idempotency_key'), table_name='intelleges_registration')
    op.drop_index(op.f('ix_intelleges_registration_email'), table_name='intelleges_registration')
    op.drop_table('intelleges_registration')
    # ### end Alembic commands ###