"""Make enterprise_id nullable in subscription

Revision ID: 9d4e760eab2d
Revises: 1668b646569e
Create Date: 2025-07-29 12:19:26.404816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4e760eab2d'
down_revision = '1668b646569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('enterprise_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('enterprise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
