"""intelleges_status

Revision ID: ca1edb24b2b4
Revises: 43d559965c80
Create Date: 2025-08-31 16:26:06.019343
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1edb24b2b4'
down_revision: Union[str, None] = '43d559965c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intelleges_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_intelleges_status'), 'users', ['intelleges_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_intelleges_status'), table_name='users')
    op.drop_column('users', 'intelleges_status')
    # ### end Alembic commands ###